#pragma once

enum options
{
    ended     = -1,
    begin     = 0,
    yes       = 0,
    grow      = 0,
    attack    = 0,
    construct = 1,
    no       = 1,
    skills   = 1,
    swap     = 1,
    main     = 1,
    activity = 2,
    lvl      = 2,
    items    = 2,
    planting = 2,
    building = 3,
    feed     = 3,
    units    = 3,
    protect  = 3,
    save     = 4,
    hire     = 4,
    working  = 4,
    quiting  = 5,
    equip    = 5,
    plantSelectorStart = 6,
    plantSelectorEnd   = 7,
    shopping  = 8,
    buy       = 9,
    sell      = 10,
    amount    = 11,
    battle    = 12,
    choosing  = 13,
    lvling    = 14,
    upgrading = 15,
    slashing  = 16,
    attacking = 17,
    equiping  = 18,
    sorting   = 19,
    healing   = 20,
    abilities = 21,
    bombing   = 22,
    firstAid  = 23
};